### ISSUE TITLE
Theme > Header menu

### ISSUE THREAD

**Issue by deneus** [Sitback/presto#103]
The css of the header menu feels weird.
It seems that the menu is displayed into a rounded rectangle, but because the menu is full with I'm expecting to see a standard rectangle.
![screen shot 2017-06-01 at 10 16 12 am](https://cloud.githubusercontent.com/assets/28583040/26659359/7159dcfc-46b3-11e7-8356-ff7e4ddf23e5.png)

**Comment by lukeoly** [comment]
This is a Drupal admin theme display issue.
