### ISSUE TITLE
Theme > Alert and Info messages

### ISSUE THREAD

**Issue by deneus** [Sitback/presto#104]
When I save my node I'm expecting to see an info message which shuould looks more than the default bootstrap one. (http://getbootstrap.com/components/#alerts)

The message should
- have the same with than the content (not being full width)
- have the same top and bottom padding (and being greater than 0)

**Comment by lukeoly** [comment]
This is looking fine to me:
![screen shot 2017-06-06 at 11 15 41 am](https://cloud.githubusercontent.com/assets/8229741/26809656/bf9c9202-4aa9-11e7-9ace-9c192a4282a3.png)
