### ISSUE TITLE
Change 'paragraph' label to 'component'

### ISSUE THREAD

**Issue by chinthakagodawita** [Sitback/presto#124]
Wherever we have a paragraph reference field, we should be change the below to be 'Component' and 'Components', respectively:

<img width="700" alt="cursor_and_manage_form_display___presto_demo" src="https://user-images.githubusercontent.com/1452384/27269543-3433078a-54fb-11e7-8936-6bf18a5b0550.png">

This _should_ affect the 'manage form display' at following places:
* Basic page content type
* Block with components block type
* Icon box list paragraph type (this may need to be 'Icon box' and 'Icon boxes')

**Comment by jrhodes-sitback** [comment]
merged into 1.1
