### ISSUE TITLE
Create Accordion/Toggle/Faq component.

### ISSUE THREAD

**Issue by khadro** [Sitback/presto#132]
Fields required (may not be exhaustive list):

- Group Title
- Multiples of:
  -- Item Name (the menu item, or question)
  -- Item Details (probably a wysiwyg field)
  -- Item starts open checkbox
- Toggle for open one at a time or open many at a time

**Comment by chinthakagodawita** [comment]
Fields LGTM 👍 

Can we call the components 'Accordion List' and 'Accordion Item'? Also make sure you can't add anything by accordion items to the list and that you can't add accordion items to pages/blocks.

**Comment by lukeoly** [comment]
I've ported the accordion templates from 132 into the Bootstrap 4 branch.

**Comment by jrhodes-sitback** [comment]
Merged into 1.1
