### ISSUE TITLE
Social icons are presenting the wrong 'idea'

### ISSUE THREAD

**Issue by khadro** [Sitback/presto#141]
From a UX perspective, social icons in the footer would generally be used for the SITE'S social media, whereas the ones in the current footer are the share links for the current page.

The icons in the footer should be changed to be links to social media, and the share icons should be exposed somewhere else on article pages (at least) so that articles (and maybe product details pages) can be shared on social networks.

Up for discussion: where we put the sharing icons, and whether this part needs to be done in 1.1

**Comment by khadro** [comment]
This should be fixed by branch `feature/141-social-media-redux`

**Comment by jrhodes-sitback** [comment]
Merged into 1.1
