### ISSUE TITLE
Create component: Divider

### ISSUE THREAD

**Issue by jrhodes-sitback** [Sitback/presto#16]
Create a component as per [documentation](https://docs.google.com/document/d/1_r3m80cfoIPqxx6cQcyQSwgQXRgXAUvxjEwqIljgyos/edit#heading=h.ds84gorrrp2o). It should be available on basic page and basic blocks.

**Comment by jrhodes-sitback** [comment]
Tested locally.

**Comment by jrhodes-sitback** [comment]
Tagging this for front-end.

**Comment by khadro** [comment]
The CSS and template changes for this are checked in to their respective repos, and ready for testing. I have built a page with all current options on it, but cannot think of a way to share this for testing purposes.

**Comment by khadro** [comment]
I think this can be closed now, it's been in for a few days now.
