### ISSUE TITLE
Adding internal link to image component throws internal error about uri not being a valid option 

### ISSUE THREAD

**Issue by khadro** [Sitback/presto#65]
`  {% set link_url = content.field_link['#items'].0.getUrl().uri %}`

This is the offending line, which works fine when an external link is used in the component.

**Comment by deneus** [comment]
Please pull the branch theme.

**Comment by chinthakagodawita** [comment]
@khadro can you close this if it's fixed in the theme branch?

**Comment by khadro** [comment]
Tested and working.
