### ISSUE TITLE
Order history/list is missing in user's profile/account page.

### ISSUE THREAD

**Issue by mlhoque** [Sitback/presto#88]
At the end of the purchase path a message is displayed that the order information is available in the user's account/profile page. But when you go to the user account and profile page, there is none.

Also, this message is displayed for both authenticated and anonymous user i.e. guest checkout. Will the order be available in user's profile page if a user registers after completing the purchase or if the user is an existing user of the site and login later?

**Comment by deneus** [comment]
Done.
PR ready

**Comment by chinthakagodawita** [comment]
Fixed by #92
